# Generated by Django 2.1.5 on 2019-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_poster_link',
            field=models.CharField(default='Not available', max_length=200),
        ),
    ]
