# Generated by Django 2.1.5 on 2019-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0002_choice_choice_poster_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='Content in writting.', max_length=300),
        ),
    ]
